# Generated by Django 5.0 on 2024-02-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='default_signature_value', max_length=140),
        ),
    ]
